# Generated by Django 4.2.29 on 2026-04-07 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_range',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='veg_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='area',
            field=models.CharField(choices=[('Bandra', 'Bandra'), ('Andheri', 'Andheri'), ('Juhu', 'Juhu'), ('Colaba', 'Colaba'), ('Dadar', 'Dadar'), ('Powai', 'Powai'), ('Worli', 'Worli'), ('Churchgate', 'Churchgate'), ('Thane', 'Thane'), ('Borivali', 'Borivali')], default='Bandra', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Continental', 'Continental'), ('Fast Food', 'Fast Food'), ('Street Food', 'Street Food'), ('Seafood', 'Seafood'), ('Mughlai', 'Mughlai'), ('South Indian', 'South Indian'), ('North Indian', 'North Indian')], default='Indian', max_length=100),
        ),
    ]
