# Generated by Django 4.2.29 on 2026-04-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_types',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
