# Generated by Django 4.2.30 on 2026-09-22 16:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DimCustomer",
            fields=[
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(default="9999-12-31")),
                ("is_current", models.BooleanField(default=True)),
                (
                    "customer_key",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("customer_id", models.BigIntegerField()),
                ("signup_cohort", models.CharField(max_length=7)),
                ("tenure_band", models.CharField(max_length=20)),
                ("rfm_segment", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "db_table": "dim_customer",
            },
        ),
        migrations.CreateModel(
            name="DimDate",
            fields=[
                ("date_key", models.BigAutoField(primary_key=True, serialize=False)),
                ("full_date", models.DateField(unique=True)),
                ("day_of_week", models.SmallIntegerField()),
                ("day_name", models.CharField(max_length=10)),
                ("month", models.SmallIntegerField()),
                ("month_name", models.CharField(max_length=10)),
                ("quarter", models.SmallIntegerField()),
                ("year", models.SmallIntegerField()),
                ("is_weekend", models.BooleanField()),
                ("festival_flag", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dim_date",
            },
        ),
        migrations.CreateModel(
            name="DimEvent",
            fields=[
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(default="9999-12-31")),
                ("is_current", models.BooleanField(default=True)),
                ("event_key", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_id", models.BigIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("genre", models.CharField(blank=True, max_length=50)),
                ("organiser", models.CharField(blank=True, max_length=255)),
                ("language", models.CharField(default="en", max_length=50)),
            ],
            options={
                "db_table": "dim_event",
            },
        ),
        migrations.CreateModel(
            name="DimLocation",
            fields=[
                (
                    "location_key",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("area", models.CharField(max_length=100)),
                ("zone", models.CharField(blank=True, max_length=50)),
                ("city", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("density_band", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "db_table": "dim_location",
            },
        ),
        migrations.CreateModel(
            name="DimMenuItem",
            fields=[
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(default="9999-12-31")),
                ("is_current", models.BooleanField(default=True)),
                ("item_key", models.BigAutoField(primary_key=True, serialize=False)),
                ("item_id", models.BigIntegerField()),
                ("item_name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("list_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("veg_flag", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dim_menu_item",
            },
        ),
        migrations.CreateModel(
            name="DimPayment",
            fields=[
                ("payment_key", models.BigAutoField(primary_key=True, serialize=False)),
                ("method", models.CharField(max_length=30, unique=True)),
                ("provider", models.CharField(blank=True, max_length=50)),
                ("is_prepaid", models.BooleanField(default=True)),
                ("settlement_band", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "db_table": "dim_payment",
            },
        ),
        migrations.CreateModel(
            name="DimPromotion",
            fields=[
                (
                    "promotion_key",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("campaign_name", models.CharField(max_length=255, unique=True)),
                ("promo_type", models.CharField(blank=True, max_length=50)),
                (
                    "discount_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("channel", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "dim_promotion",
            },
        ),
        migrations.CreateModel(
            name="DimRestaurant",
            fields=[
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(default="9999-12-31")),
                ("is_current", models.BooleanField(default=True)),
                (
                    "restaurant_key",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("restaurant_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("cuisine", models.CharField(blank=True, max_length=255)),
                ("price_band", models.CharField(blank=True, max_length=20)),
                ("area", models.CharField(blank=True, max_length=100)),
                ("rating_band", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "db_table": "dim_restaurant",
            },
        ),
        migrations.CreateModel(
            name="DimTicketType",
            fields=[
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(default="9999-12-31")),
                ("is_current", models.BooleanField(default=True)),
                (
                    "ticket_type_key",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("ticket_type_id", models.BigIntegerField()),
                ("class_name", models.CharField(max_length=100)),
                ("tier", models.CharField(blank=True, max_length=50)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_refundable", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "dim_ticket_type",
            },
        ),
        migrations.CreateModel(
            name="DimTime",
            fields=[
                ("time_key", models.BigAutoField(primary_key=True, serialize=False)),
                ("hour", models.SmallIntegerField()),
                ("minute_band", models.SmallIntegerField()),
                ("day_part", models.CharField(max_length=20)),
                ("is_peak_hour", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dim_time",
                "unique_together": {("hour", "minute_band")},
            },
        ),
        migrations.CreateModel(
            name="DimVenue",
            fields=[
                ("venue_key", models.BigAutoField(primary_key=True, serialize=False)),
                ("venue_id", models.BigIntegerField(unique=True)),
                ("venue_name", models.CharField(max_length=255)),
                ("capacity_band", models.CharField(blank=True, max_length=20)),
                ("zone", models.CharField(blank=True, max_length=50)),
                ("city", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "dim_venue",
            },
        ),
        migrations.CreateModel(
            name="FactTicketSale",
            fields=[
                ("fact_key", models.BigAutoField(primary_key=True, serialize=False)),
                ("ticket_id", models.BigIntegerField(unique=True)),
                (
                    "ticket_revenue",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "convenience_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("seat_tier_rank", models.SmallIntegerField()),
                ("is_no_show", models.BooleanField(default=False)),
                ("loaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        db_column="customer_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimcustomer",
                    ),
                ),
                (
                    "date",
                    models.ForeignKey(
                        db_column="date_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimdate",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        db_column="event_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimevent",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        db_column="payment_key",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimpayment",
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        db_column="ticket_type_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimtickettype",
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        db_column="time_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimtime",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        db_column="venue_key",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimvenue",
                    ),
                ),
            ],
            options={
                "db_table": "fact_ticket_sale",
            },
        ),
        migrations.CreateModel(
            name="FactOrderItem",
            fields=[
                ("fact_key", models.BigAutoField(primary_key=True, serialize=False)),
                ("order_item_id", models.BigIntegerField(unique=True)),
                ("quantity", models.IntegerField()),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("loaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        db_column="customer_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimcustomer",
                    ),
                ),
                (
                    "date",
                    models.ForeignKey(
                        db_column="date_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimdate",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        db_column="item_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimmenuitem",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        db_column="restaurant_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimrestaurant",
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        db_column="time_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimtime",
                    ),
                ),
            ],
            options={
                "db_table": "fact_order_item",
            },
        ),
        migrations.CreateModel(
            name="FactOrder",
            fields=[
                ("fact_key", models.BigAutoField(primary_key=True, serialize=False)),
                ("order_id", models.UUIDField(unique=True)),
                ("order_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("item_count", models.IntegerField()),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "discount_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("delivery_minutes", models.IntegerField(blank=True, null=True)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("loaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        db_column="customer_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimcustomer",
                    ),
                ),
                (
                    "date",
                    models.ForeignKey(
                        db_column="date_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimdate",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        db_column="location_key",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimlocation",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        db_column="payment_key",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimpayment",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        blank=True,
                        db_column="promotion_key",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimpromotion",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        db_column="restaurant_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimrestaurant",
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        db_column="time_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimtime",
                    ),
                ),
            ],
            options={
                "db_table": "fact_order",
            },
        ),
        migrations.CreateModel(
            name="FactBooking",
            fields=[
                ("fact_key", models.BigAutoField(primary_key=True, serialize=False)),
                ("booking_id", models.BigIntegerField(unique=True)),
                ("booking_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("seats_booked", models.IntegerField()),
                ("lead_time_days", models.FloatField()),
                ("is_cancelled", models.BooleanField(default=False)),
                ("is_no_show", models.BooleanField(default=False)),
                ("loaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        db_column="customer_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimcustomer",
                    ),
                ),
                (
                    "date",
                    models.ForeignKey(
                        db_column="date_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimdate",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        db_column="event_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimevent",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        db_column="payment_key",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimpayment",
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        db_column="time_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimtime",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        db_column="venue_key",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimvenue",
                    ),
                ),
            ],
            options={
                "db_table": "fact_booking",
            },
        ),
        migrations.CreateModel(
            name="EtlRunAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("table_name", models.CharField(max_length=100)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("window_from", models.DateTimeField(blank=True, null=True)),
                ("window_to", models.DateTimeField(blank=True, null=True)),
                ("rows_read", models.IntegerField(default=0)),
                ("rows_rejected", models.IntegerField(default=0)),
                ("rows_loaded", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "db_table": "etl_run_audit",
                "indexes": [
                    models.Index(
                        fields=["run_id"], name="etl_run_aud_run_id_6d6020_idx"
                    ),
                    models.Index(
                        fields=["table_name"], name="etl_run_aud_table_n_a5cf5a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EtlQuarantine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.UUIDField()),
                ("table_name", models.CharField(max_length=100)),
                ("source_pk", models.CharField(max_length=64)),
                ("violated_rule", models.CharField(max_length=100)),
                ("raw_row", models.JSONField(blank=True, default=dict)),
                ("quarantined_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "etl_quarantine",
                "indexes": [
                    models.Index(
                        fields=["run_id"], name="etl_quarant_run_id_310317_idx"
                    ),
                    models.Index(
                        fields=["table_name"], name="etl_quarant_table_n_12e2bd_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="dimtickettype",
            index=models.Index(
                fields=["ticket_type_id"], name="dim_ticket__ticket__af9019_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dimtickettype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("ticket_type_id",),
                name="uq_dim_ticket_type_current",
            ),
        ),
        migrations.AddIndex(
            model_name="dimrestaurant",
            index=models.Index(
                fields=["restaurant_id"], name="dim_restaur_restaur_a7afcd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dimrestaurant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("restaurant_id",),
                name="uq_dim_restaurant_current",
            ),
        ),
        migrations.AddIndex(
            model_name="dimmenuitem",
            index=models.Index(
                fields=["item_id"], name="dim_menu_it_item_id_16a977_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dimmenuitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("item_id",),
                name="uq_dim_menu_item_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="dimlocation",
            constraint=models.UniqueConstraint(
                fields=("area", "city"), name="uq_dim_location_area_city"
            ),
        ),
        migrations.AddIndex(
            model_name="dimevent",
            index=models.Index(
                fields=["event_id"], name="dim_event_event_i_25a714_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dimevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("event_id",),
                name="uq_dim_event_current",
            ),
        ),
        migrations.AddIndex(
            model_name="dimcustomer",
            index=models.Index(
                fields=["customer_id"], name="dim_custome_custome_b1d371_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dimcustomer",
            index=models.Index(
                fields=["customer_id", "is_current"],
                name="dim_custome_custome_ec915a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="dimcustomer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("customer_id",),
                name="uq_dim_customer_current",
            ),
        ),
        migrations.AddIndex(
            model_name="factticketsale",
            index=models.Index(fields=["date"], name="fact_ticket_date_ke_059588_idx"),
        ),
        migrations.AddIndex(
            model_name="factticketsale",
            index=models.Index(fields=["event"], name="fact_ticket_event_k_3a3a8d_idx"),
        ),
        migrations.AddIndex(
            model_name="factticketsale",
            index=models.Index(
                fields=["ticket_type"], name="fact_ticket_ticket__147cd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factorderitem",
            index=models.Index(fields=["date"], name="fact_order__date_ke_06cf1b_idx"),
        ),
        migrations.AddIndex(
            model_name="factorderitem",
            index=models.Index(
                fields=["menu_item"], name="fact_order__item_ke_6eadb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factorder",
            index=models.Index(fields=["date"], name="fact_order_date_ke_6c3d07_idx"),
        ),
        migrations.AddIndex(
            model_name="factorder",
            index=models.Index(
                fields=["customer"], name="fact_order_custome_2d3063_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factorder",
            index=models.Index(
                fields=["restaurant"], name="fact_order_restaur_9e7ddc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factbooking",
            index=models.Index(fields=["date"], name="fact_bookin_date_ke_b96585_idx"),
        ),
        migrations.AddIndex(
            model_name="factbooking",
            index=models.Index(
                fields=["customer"], name="fact_bookin_custome_7e2d4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factbooking",
            index=models.Index(fields=["event"], name="fact_bookin_event_k_d77054_idx"),
        ),
    ]
