# Generated by Django 4.2.30 on 2026-09-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CbDailyEventSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("event_id", models.BigIntegerField()),
                ("event_title", models.CharField(max_length=255)),
                ("venue_id", models.BigIntegerField(null=True)),
                ("ticket_type_id", models.BigIntegerField()),
                ("tier_name", models.CharField(max_length=100)),
                (
                    "net_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("tickets_sold", models.IntegerField(default=0)),
                ("refreshed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cb_daily_event_sales",
            },
        ),
        migrations.CreateModel(
            name="CbDailyItemPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("menu_item_id", models.BigIntegerField()),
                ("item_name", models.CharField(max_length=255)),
                ("restaurant_id", models.BigIntegerField()),
                (
                    "net_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("quantity_sold", models.IntegerField(default=0)),
                ("refreshed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cb_daily_item_performance",
            },
        ),
        migrations.CreateModel(
            name="CbDailyOutletRevenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("restaurant_id", models.BigIntegerField()),
                ("restaurant_name", models.CharField(max_length=255)),
                ("area", models.CharField(blank=True, max_length=100)),
                (
                    "net_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("order_count", models.IntegerField(default=0)),
                ("item_count", models.IntegerField(default=0)),
                ("refreshed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cb_daily_outlet_revenue",
            },
        ),
        migrations.CreateModel(
            name="CbHourlyDemandProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("day_part", models.CharField(max_length=20)),
                ("area", models.CharField(blank=True, max_length=100)),
                ("domain", models.CharField(max_length=10)),
                ("transaction_count", models.IntegerField(default=0)),
                (
                    "net_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("refreshed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cb_hourly_demand_profile",
            },
        ),
        migrations.CreateModel(
            name="CbMonthlyCustomerActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=7)),
                ("customer_id", models.BigIntegerField()),
                ("domain", models.CharField(max_length=10)),
                (
                    "total_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("transaction_count", models.IntegerField(default=0)),
                ("last_transaction_date", models.DateField(blank=True, null=True)),
                ("refreshed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cb_monthly_customer_activity",
                "indexes": [
                    models.Index(fields=["month"], name="cb_monthly__month_d09037_idx"),
                    models.Index(
                        fields=["customer_id"], name="cb_monthly__custome_d25ef3_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="cbmonthlycustomeractivity",
            constraint=models.UniqueConstraint(
                fields=("month", "customer_id", "domain"),
                name="uq_cb_customer_activity",
            ),
        ),
        migrations.AddIndex(
            model_name="cbhourlydemandprofile",
            index=models.Index(fields=["date"], name="cb_hourly_d_date_84bd12_idx"),
        ),
        migrations.AddConstraint(
            model_name="cbhourlydemandprofile",
            constraint=models.UniqueConstraint(
                fields=("date", "day_part", "area", "domain"),
                name="uq_cb_demand_profile",
            ),
        ),
        migrations.AddIndex(
            model_name="cbdailyoutletrevenue",
            index=models.Index(fields=["date"], name="cb_daily_ou_date_0e4a67_idx"),
        ),
        migrations.AddIndex(
            model_name="cbdailyoutletrevenue",
            index=models.Index(
                fields=["restaurant_id"], name="cb_daily_ou_restaur_533639_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cbdailyoutletrevenue",
            constraint=models.UniqueConstraint(
                fields=("date", "restaurant_id"), name="uq_cb_outlet_rev"
            ),
        ),
        migrations.AddIndex(
            model_name="cbdailyitemperformance",
            index=models.Index(fields=["date"], name="cb_daily_it_date_04214c_idx"),
        ),
        migrations.AddIndex(
            model_name="cbdailyitemperformance",
            index=models.Index(
                fields=["menu_item_id"], name="cb_daily_it_menu_it_c1b2be_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cbdailyitemperformance",
            constraint=models.UniqueConstraint(
                fields=("date", "menu_item_id", "restaurant_id"), name="uq_cb_item_perf"
            ),
        ),
        migrations.AddIndex(
            model_name="cbdailyeventsales",
            index=models.Index(fields=["date"], name="cb_daily_ev_date_8c7e72_idx"),
        ),
        migrations.AddIndex(
            model_name="cbdailyeventsales",
            index=models.Index(
                fields=["event_id"], name="cb_daily_ev_event_i_6959c9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cbdailyeventsales",
            constraint=models.UniqueConstraint(
                fields=("date", "event_id", "ticket_type_id"), name="uq_cb_event_sales"
            ),
        ),
    ]
