# Generated by Django 4.2.30 on 2026-09-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_cbdailyeventsales_cbdailyitemperformance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factorderitem",
            name="order_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="factorderitem",
            index=models.Index(
                fields=["order_id"], name="fact_order__order_i_952694_idx"
            ),
        ),
    ]
