# Generated by Django 4.2.30 on 2026-10-01 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0003_factorderitem_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimevent",
            name="event_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimevent",
            name="organizer_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimevent",
            name="total_seats",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dimpromotion",
            name="promotion_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimpromotion",
            name="restaurant_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimpromotion",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimpromotion",
            name="valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimrestaurant",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="dimrestaurant",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimrestaurant",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimtickettype",
            name="capacity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dimvenue",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimvenue",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="etlrunaudit",
            name="high_water_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="factorder",
            name="failed_payments",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="FactSearch",
            fields=[
                ("fact_key", models.BigAutoField(primary_key=True, serialize=False)),
                ("search_log_id", models.BigIntegerField(unique=True)),
                ("query_text", models.CharField(max_length=255)),
                ("normalized_query", models.CharField(db_index=True, max_length=255)),
                ("scope", models.CharField(blank=True, max_length=20)),
                ("has_results", models.BooleanField(blank=True, null=True)),
                ("clicked", models.BooleanField(default=False)),
                ("loaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "date",
                    models.ForeignKey(
                        db_column="date_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimdate",
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        db_column="time_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimtime",
                    ),
                ),
            ],
            options={
                "db_table": "fact_search",
            },
        ),
        migrations.CreateModel(
            name="FactPayout",
            fields=[
                ("fact_key", models.BigAutoField(primary_key=True, serialize=False)),
                ("payout_id", models.BigIntegerField(unique=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("order_count", models.IntegerField(default=0)),
                (
                    "gross_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("status", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("days_to_pay", models.FloatField(blank=True, null=True)),
                ("loaded_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        db_column="restaurant_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimrestaurant",
                    ),
                ),
            ],
            options={
                "db_table": "fact_payout",
            },
        ),
        migrations.CreateModel(
            name="FactOrderLifecycle",
            fields=[
                ("fact_key", models.BigAutoField(primary_key=True, serialize=False)),
                ("order_id", models.UUIDField(unique=True)),
                ("placed_at", models.DateTimeField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("preparing_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("accept_minutes", models.FloatField(blank=True, null=True)),
                ("prep_minutes", models.FloatField(blank=True, null=True)),
                ("handoff_minutes", models.FloatField(blank=True, null=True)),
                ("transit_minutes", models.FloatField(blank=True, null=True)),
                ("total_minutes", models.FloatField(blank=True, null=True)),
                ("item_count", models.IntegerField(default=0)),
                ("current_status", models.CharField(max_length=20)),
                ("is_complete", models.BooleanField(default=False)),
                ("loaded_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        db_column="customer_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimcustomer",
                    ),
                ),
                (
                    "date",
                    models.ForeignKey(
                        db_column="date_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimdate",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        db_column="restaurant_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimrestaurant",
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        db_column="time_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimtime",
                    ),
                ),
            ],
            options={
                "db_table": "fact_order_lifecycle",
            },
        ),
        migrations.CreateModel(
            name="DataQualityCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.UUIDField()),
                ("check_name", models.CharField(max_length=100)),
                ("table_name", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("pass", "Pass"), ("warn", "Warn"), ("fail", "Fail")],
                        max_length=10,
                    ),
                ),
                ("observed", models.FloatField(blank=True, null=True)),
                ("threshold", models.FloatField(blank=True, null=True)),
                ("message", models.CharField(blank=True, max_length=255)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "etl_data_quality_check",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["run_id"], name="etl_data_qu_run_id_7bbec3_idx"
                    ),
                    models.Index(
                        fields=["check_name", "checked_at"],
                        name="etl_data_qu_check_n_e11cfb_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FactSeatInventorySnapshot",
            fields=[
                ("fact_key", models.BigAutoField(primary_key=True, serialize=False)),
                ("natural_event_id", models.BigIntegerField()),
                ("natural_ticket_type_id", models.BigIntegerField()),
                ("capacity", models.IntegerField()),
                ("sold", models.IntegerField()),
                ("held", models.IntegerField(default=0)),
                ("available", models.IntegerField()),
                ("days_to_event", models.IntegerField()),
                ("loaded_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        db_column="event_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimevent",
                    ),
                ),
                (
                    "snapshot_date",
                    models.ForeignKey(
                        db_column="date_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimdate",
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        db_column="ticket_type_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.dimtickettype",
                    ),
                ),
            ],
            options={
                "db_table": "fact_seat_inventory_snapshot",
                "indexes": [
                    models.Index(
                        fields=["natural_event_id"],
                        name="fact_seat_i_natural_a4b927_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="factseatinventorysnapshot",
            constraint=models.UniqueConstraint(
                fields=("snapshot_date", "natural_ticket_type_id"),
                name="uq_seat_snapshot_day_tier",
            ),
        ),
        migrations.AddIndex(
            model_name="factsearch",
            index=models.Index(fields=["date"], name="fact_search_date_ke_a7e416_idx"),
        ),
        migrations.AddIndex(
            model_name="factpayout",
            index=models.Index(
                fields=["restaurant"], name="fact_payout_restaur_eff18c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factpayout",
            index=models.Index(fields=["status"], name="fact_payout_status_4d89a2_idx"),
        ),
        migrations.AddIndex(
            model_name="factorderlifecycle",
            index=models.Index(fields=["date"], name="fact_order__date_ke_c259fd_idx"),
        ),
        migrations.AddIndex(
            model_name="factorderlifecycle",
            index=models.Index(
                fields=["restaurant"], name="fact_order__restaur_ee450c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factorderlifecycle",
            index=models.Index(
                fields=["current_status"], name="fact_order__current_97dadb_idx"
            ),
        ),
    ]
