# Generated by Django 4.2.30 on 2026-10-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0004_lifecycle_search_payout_snapshot_quality"),
    ]

    operations = [
        migrations.AddField(
            model_name="factsearch",
            name="vertical",
            field=models.CharField(default="unknown", max_length=10),
        ),
    ]
