# Generated by Django 4.2.30 on 2026-09-22 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MiningRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=30)),
                ("model_version", models.CharField(max_length=20)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "db_table": "mining_run",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["module", "started_at"],
                        name="mining_run_module_153c24_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MiningBasketRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restaurant_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[("item", "Item"), ("category", "Category")],
                        max_length=10,
                    ),
                ),
                ("antecedent", models.JSONField()),
                ("consequent", models.JSONField()),
                ("support", models.FloatField()),
                ("confidence", models.FloatField()),
                ("lift", models.FloatField()),
                ("conviction", models.FloatField(blank=True, null=True)),
                ("model_version", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basket_rules",
                        to="mining.miningrun",
                    ),
                ),
            ],
            options={
                "db_table": "mining_basket_rule",
            },
        ),
        migrations.CreateModel(
            name="MiningCustomerSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.BigIntegerField()),
                ("segment_label", models.CharField(max_length=30)),
                ("recency_days", models.FloatField()),
                ("frequency", models.IntegerField()),
                ("monetary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("confidence", models.FloatField()),
                ("model_version", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_segments",
                        to="mining.miningrun",
                    ),
                ),
            ],
            options={
                "db_table": "mining_customer_segment",
                "indexes": [
                    models.Index(
                        fields=["customer_id"], name="mining_cust_custome_569f6b_idx"
                    ),
                    models.Index(
                        fields=["segment_label"], name="mining_cust_segment_4a8e8d_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="miningcustomersegment",
            constraint=models.UniqueConstraint(
                fields=("run", "customer_id"), name="uq_mining_segment_run_customer"
            ),
        ),
        migrations.AddIndex(
            model_name="miningbasketrule",
            index=models.Index(
                fields=["restaurant_id"], name="mining_bask_restaur_fa63d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="miningbasketrule",
            index=models.Index(fields=["level"], name="mining_bask_level_391b1c_idx"),
        ),
        migrations.AddIndex(
            model_name="miningbasketrule",
            index=models.Index(fields=["lift"], name="mining_bask_lift_cf7fae_idx"),
        ),
    ]
