# Generated by Django 4.2.30 on 2026-10-01 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mining", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MiningPriceElasticity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("elasticity", models.FloatField()),
                ("r_squared", models.FloatField()),
                ("events", models.IntegerField()),
                ("tiers", models.IntegerField()),
                ("avg_sell_through", models.FloatField()),
                ("median_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("advice", models.CharField(max_length=255)),
                ("model_version", models.CharField(max_length=20)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_elasticities",
                        to="mining.miningrun",
                    ),
                ),
            ],
            options={
                "db_table": "mining_price_elasticity",
            },
        ),
        migrations.CreateModel(
            name="MiningHotspot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[("zesty", "Zesty"), ("eventra", "Eventra")],
                        max_length=10,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("label", models.CharField(max_length=255)),
                ("center_lat", models.FloatField()),
                ("center_lng", models.FloatField()),
                ("radius_km", models.FloatField()),
                ("demand", models.IntegerField()),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("supply", models.IntegerField()),
                ("demand_per_supply", models.FloatField()),
                ("avg_delivery_minutes", models.FloatField(blank=True, null=True)),
                ("opportunity", models.CharField(max_length=20)),
                ("model_version", models.CharField(max_length=20)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotspots",
                        to="mining.miningrun",
                    ),
                ),
            ],
            options={
                "db_table": "mining_hotspot",
            },
        ),
        migrations.CreateModel(
            name="MiningSequenceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("antecedent", models.CharField(max_length=100)),
                ("consequent", models.CharField(max_length=100)),
                ("window_hours", models.IntegerField()),
                ("occurrences", models.IntegerField()),
                ("support", models.FloatField()),
                ("confidence", models.FloatField()),
                ("lift", models.FloatField()),
                ("model_version", models.CharField(max_length=20)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequence_rules",
                        to="mining.miningrun",
                    ),
                ),
            ],
            options={
                "db_table": "mining_sequence_rule",
                "indexes": [
                    models.Index(
                        fields=["run", "lift"], name="mining_sequ_run_id_e18ca5_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MiningSellOutForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.BigIntegerField()),
                ("organizer_id", models.BigIntegerField(blank=True, null=True)),
                ("event_date", models.DateTimeField()),
                ("capacity", models.IntegerField()),
                ("sold", models.IntegerField()),
                ("sold_last_7d", models.IntegerField(default=0)),
                ("days_to_event", models.IntegerField()),
                ("projected_final", models.IntegerField()),
                ("projected_sell_through", models.FloatField()),
                ("sell_out_probability", models.FloatField()),
                ("projected_sell_out_date", models.DateField(blank=True, null=True)),
                ("model_version", models.CharField(max_length=20)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sellout_forecasts",
                        to="mining.miningrun",
                    ),
                ),
            ],
            options={
                "db_table": "mining_sellout_forecast",
                "indexes": [
                    models.Index(
                        fields=["run", "event_id"], name="mining_sell_run_id_f558ab_idx"
                    ),
                    models.Index(
                        fields=["organizer_id"], name="mining_sell_organiz_0c9498_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MiningSearchTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=255)),
                ("cluster", models.CharField(max_length=255)),
                ("searches", models.IntegerField()),
                ("searches_7d", models.IntegerField(default=0)),
                ("trend", models.FloatField()),
                ("zero_result_rate", models.FloatField(blank=True, null=True)),
                ("click_rate", models.FloatField(blank=True, null=True)),
                ("flag", models.CharField(blank=True, max_length=20)),
                ("model_version", models.CharField(max_length=20)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_terms",
                        to="mining.miningrun",
                    ),
                ),
            ],
            options={
                "db_table": "mining_search_term",
                "indexes": [
                    models.Index(
                        fields=["run", "flag"], name="mining_sear_run_id_d43b9e_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MiningRiskScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("booking_no_show", "Booking no-show"),
                            ("booking_cancellation", "Booking cancellation"),
                            ("order_cancellation", "Order cancellation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target_id", models.CharField(max_length=64)),
                ("entity_id", models.BigIntegerField(blank=True, null=True)),
                ("customer_id", models.BigIntegerField(blank=True, null=True)),
                ("seats", models.IntegerField(default=1)),
                ("probability", models.FloatField()),
                ("band", models.CharField(max_length=10)),
                ("model_version", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_scores",
                        to="mining.miningrun",
                    ),
                ),
            ],
            options={
                "db_table": "mining_risk_score",
                "indexes": [
                    models.Index(
                        fields=["run", "kind", "entity_id"],
                        name="mining_risk_run_id_eadab1_idx",
                    ),
                    models.Index(
                        fields=["target_id"], name="mining_risk_target__bd70a1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MiningRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.BigIntegerField()),
                (
                    "domain",
                    models.CharField(
                        choices=[("food", "Food"), ("event", "Event")], max_length=10
                    ),
                ),
                ("item_id", models.BigIntegerField(blank=True, null=True)),
                ("label", models.CharField(max_length=255)),
                ("score", models.FloatField()),
                ("rank", models.IntegerField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("model_version", models.CharField(max_length=20)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="mining.miningrun",
                    ),
                ),
            ],
            options={
                "db_table": "mining_recommendation",
                "indexes": [
                    models.Index(
                        fields=["run", "customer_id", "domain"],
                        name="mining_reco_run_id_9bb197_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MiningPromoEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("promo_code", models.CharField(max_length=255)),
                ("restaurant_id", models.BigIntegerField(blank=True, null=True)),
                ("window_start", models.DateField()),
                ("window_end", models.DateField()),
                ("redemptions", models.IntegerField()),
                (
                    "discount_given",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("orders_per_day_before", models.FloatField()),
                ("orders_per_day_during", models.FloatField()),
                ("uplift_pct", models.FloatField(blank=True, null=True)),
                ("incremental_orders", models.FloatField(blank=True, null=True)),
                (
                    "incremental_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("roi", models.FloatField(blank=True, null=True)),
                ("p_value", models.FloatField(blank=True, null=True)),
                ("verdict", models.CharField(max_length=20)),
                ("model_version", models.CharField(max_length=20)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_effects",
                        to="mining.miningrun",
                    ),
                ),
            ],
            options={
                "db_table": "mining_promo_effect",
                "indexes": [
                    models.Index(
                        fields=["run", "restaurant_id"],
                        name="mining_prom_run_id_8aabff_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MiningForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        choices=[
                            ("restaurant_orders", "Restaurant orders"),
                            ("platform_orders", "Platform orders"),
                            ("platform_bookings", "Platform bookings"),
                        ],
                        max_length=30,
                    ),
                ),
                ("entity_id", models.BigIntegerField(blank=True, null=True)),
                ("target_date", models.DateField()),
                ("predicted", models.FloatField()),
                ("lower", models.FloatField()),
                ("upper", models.FloatField()),
                ("model_version", models.CharField(max_length=20)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="mining.miningrun",
                    ),
                ),
            ],
            options={
                "db_table": "mining_forecast",
                "indexes": [
                    models.Index(
                        fields=["run", "series", "entity_id"],
                        name="mining_fore_run_id_e080e5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MiningDeliveryEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restaurant_id", models.BigIntegerField()),
                ("day_part", models.CharField(max_length=20)),
                ("is_weekend", models.BooleanField()),
                ("size_band", models.CharField(max_length=10)),
                ("predicted_minutes", models.FloatField()),
                ("p90_minutes", models.FloatField()),
                ("model_version", models.CharField(max_length=20)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_estimates",
                        to="mining.miningrun",
                    ),
                ),
            ],
            options={
                "db_table": "mining_delivery_estimate",
                "indexes": [
                    models.Index(
                        fields=["run", "restaurant_id"],
                        name="mining_deli_run_id_f66b3f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MiningCustomerScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.BigIntegerField()),
                ("churn_probability", models.FloatField(blank=True, null=True)),
                ("churn_band", models.CharField(blank=True, max_length=10)),
                (
                    "predicted_90d_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "historic_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("value_band", models.CharField(blank=True, max_length=10)),
                ("days_since_last", models.IntegerField()),
                ("purchases_90d", models.IntegerField(default=0)),
                ("top_reason", models.CharField(blank=True, max_length=255)),
                ("model_version", models.CharField(max_length=20)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_scores",
                        to="mining.miningrun",
                    ),
                ),
            ],
            options={
                "db_table": "mining_customer_score",
                "indexes": [
                    models.Index(
                        fields=["run", "customer_id"],
                        name="mining_cust_run_id_5c05f3_idx",
                    ),
                    models.Index(
                        fields=["run", "churn_band"],
                        name="mining_cust_run_id_238eef_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MiningAnomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[("order", "Order"), ("booking", "Booking")],
                        max_length=10,
                    ),
                ),
                ("target_id", models.CharField(max_length=64)),
                ("customer_id", models.BigIntegerField(blank=True, null=True)),
                ("entity_id", models.BigIntegerField(blank=True, null=True)),
                ("occurred_on", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("score", models.FloatField()),
                ("rank", models.IntegerField()),
                ("reasons", models.JSONField(default=list)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("confirmed", "Confirmed"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("reviewed_by", models.BigIntegerField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("model_version", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="mining.miningrun",
                    ),
                ),
            ],
            options={
                "db_table": "mining_anomaly",
                "indexes": [
                    models.Index(
                        fields=["run", "rank"], name="mining_anom_run_id_f2edb3_idx"
                    ),
                    models.Index(
                        fields=["domain", "target_id"],
                        name="mining_anom_domain_de9cef_idx",
                    ),
                ],
            },
        ),
    ]
