# Generated by Django 4.2.30 on 2026-10-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mining", "0002_mining_set_b"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="miningcustomersegment",
            name="uq_mining_segment_run_customer",
        ),
        migrations.RemoveIndex(
            model_name="miningcustomerscore",
            name="mining_cust_run_id_5c05f3_idx",
        ),
        migrations.RemoveIndex(
            model_name="miningcustomerscore",
            name="mining_cust_run_id_238eef_idx",
        ),
        migrations.AddField(
            model_name="miningcustomerscore",
            name="vertical",
            field=models.CharField(default="all", max_length=10),
        ),
        migrations.AddField(
            model_name="miningcustomersegment",
            name="vertical",
            field=models.CharField(default="all", max_length=10),
        ),
        migrations.AddField(
            model_name="miningsearchterm",
            name="vertical",
            field=models.CharField(default="unknown", max_length=10),
        ),
        migrations.AddIndex(
            model_name="miningcustomerscore",
            index=models.Index(
                fields=["run", "vertical", "customer_id"],
                name="mining_cust_run_id_31a306_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="miningcustomerscore",
            index=models.Index(
                fields=["run", "vertical", "churn_band"],
                name="mining_cust_run_id_0e8b6f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="miningcustomersegment",
            constraint=models.UniqueConstraint(
                fields=("run", "vertical", "customer_id"),
                name="uq_mining_segment_run_vertical_customer",
            ),
        ),
    ]
