/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
        "colors": {
        "eventra": {
          "bg": "#0A0A0A",
          "surface": "#141414",
          "amber": "#C4621A",
          "amberLight": "#E8824A",
          "text": "#F5F0E8",
          "muted": "#9A9A9A",
          "white": "#FFFFFF",
          "tickerBg": "#A0521A"
        },
            "eventra-on-primary-container": "#f3ecff",
            "eventra-inverse-on-surface": "#f2f0f6",
            "eventra-secondary-fixed": "#e4e2e4",
            "eventra-on-error": "#ffffff",
            "eventra-surface-container-high": "#e9e7ed",
            "eventra-primary": "#5426e4",
            "eventra-on-primary": "#ffffff",
            "eventra-primary-container": "#6d49fd",
            "eventra-outline": "#797587",
            "eventra-primary-fixed-dim": "#c9beff",
            "eventra-on-primary-fixed": "#1b0063",
            "eventra-secondary": "#5f5e60",
            "eventra-tertiary-fixed-dim": "#c8c3dd",
            "eventra-surface-variant": "#e3e1e7",
            "eventra-on-tertiary-fixed-variant": "#474459",
            "eventra-surface-dim": "#dbd9df",
            "eventra-on-secondary-fixed-variant": "#474649",
            "eventra-tertiary-fixed": "#e4dff9",
            "eventra-on-tertiary": "#ffffff",
            "eventra-surface-container-lowest": "#ffffff",
            "eventra-on-primary-fixed-variant": "#4600d7",
            "eventra-primary-fixed": "#e6deff",
            "eventra-on-surface": "#1b1b20",
            "eventra-inverse-primary": "#c9beff",
            "eventra-on-secondary-fixed": "#1b1b1d",
            "eventra-on-secondary": "#ffffff",
            "eventra-surface-container": "#efedf3",
            "eventra-error": "#ba1a1a",
            "eventra-on-tertiary-fixed": "#1b192c",
            "eventra-surface-container-highest": "#e3e1e7",
            "eventra-background": "#fbf8fe",
            "eventra-surface-container-low": "#f5f3f9",
            "eventra-surface": "#fbf8fe",
            "eventra-on-secondary-container": "#636264",
            "eventra-inverse-surface": "#303035",
            "eventra-surface-tint": "#5e36ee",
            "eventra-tertiary-container": "#6d6a80",
            "eventra-error-container": "#ffdad6",
            "eventra-secondary-container": "#e2dfe1",
            "eventra-on-background": "#1b1b20",
            "eventra-secondary-fixed-dim": "#c8c6c8",
            "eventra-outline-variant": "#c9c3d9",
            "eventra-on-surface-variant": "#484556",
            "eventra-on-tertiary-container": "#f2edff",
            "eventra-surface-bright": "#fbf8fe",
            "eventra-on-error-container": "#93000a",
            "eventra-tertiary": "#545267",
            "outline": "#8f6f6e",
            "surface-dim": "#dcd9d9",
            "inverse-surface": "#313030",
            "surface-container-high": "#eae7e7",
            "on-tertiary": "#ffffff",
            "surface-container": "#f0eded",
            "secondary-fixed-dim": "#c8c6c5",
            "on-primary-container": "#fffbff",
            "surface-bright": "#fcf9f8",
            "inverse-primary": "#ffb3b1",
            "surface": "#fcf9f8",
            "tertiary-fixed": "#f0dee0",
            "on-secondary-fixed": "#1b1b1b",
            "on-error-container": "#93000a",
            "tertiary": "#65595b",
            "surface-container-highest": "#e5e2e1",
            "tertiary-fixed-dim": "#d3c3c5",
            "inverse-on-surface": "#f3f0ef",
            "on-surface": "#1b1b1b",
            "on-tertiary-fixed-variant": "#4f4446",
            "secondary-fixed": "#e5e2e1",
            "on-secondary-container": "#636262",
            "primary": "#b7122a",
            "error": "#ba1a1a",
            "primary-container": "#db313f",
            "on-primary": "#ffffff",
            "tertiary-container": "#7f7173",
            "background": "#fcf9f8",
            "surface-variant": "#e5e2e1",
            "on-surface-variant": "#5b403f",
            "on-primary-fixed": "#410007",
            "secondary": "#5f5e5e",
            "on-primary-fixed-variant": "#92001c",
            "on-tertiary-fixed": "#22191b",
            "error-container": "#ffdad6",
            "on-background": "#1b1b1b",
            "on-error": "#ffffff",
            "secondary-container": "#e2dfde",
            "surface-container-lowest": "#ffffff",
            "on-secondary": "#ffffff",
            "primary-fixed": "#ffdad8",
            "surface-tint": "#bb162c",
            "primary-fixed-dim": "#ffb3b1",
            "surface-container-low": "#f6f3f2",
            "on-tertiary-container": "#fffbff",
            "on-secondary-fixed-variant": "#474746",
            "outline-variant": "#e4bebc"
        },
        "borderRadius": {
            "DEFAULT": "0.25rem",
            "lg": "0.5rem",
            "xl": "0.75rem",
            "2xl": "1.5rem",
            "full": "9999px"
        },
        "fontFamily": {
            "eventra-headline": ["Inter", "sans-serif"],
            "eventra-body": ["Inter", "sans-serif"],
          "eventra-display": ["Playfair Display", "serif"],
          "eventra-premium-body": ["Inter", "sans-serif"],
            "eventra-label": ["Be Vietnam Pro", "sans-serif"],
            "headline": ["Lexend", "sans-serif"],
            "body": ["Lexend", "sans-serif"],
            "label": ["Lexend", "sans-serif"],
             "lexend": ["Lexend", "sans-serif"]
        }
    }
  },
  plugins: [],
}
