# Generated by Django 4.2.30 on 2026-09-21 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eventra", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qr_token",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("is_scanned", models.BooleanField(default=False)),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                ("scanned_gate", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="eventra.booking",
                    ),
                ),
                (
                    "seat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket",
                        to="eventra.seat",
                    ),
                ),
            ],
            options={
                "db_table": "tickets",
            },
        ),
        migrations.AddField(
            model_name="tickettype",
            name="is_refundable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tickettype",
            name="refund_cutoff_hours",
            field=models.IntegerField(
                default=24,
                help_text="Cancellation is refused within this many hours of the event.",
            ),
        ),
        migrations.CreateModel(
            name="TicketScanAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("was_accepted", models.BooleanField()),
                ("gate", models.CharField(blank=True, max_length=50)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_attempts",
                        to="eventra.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "ticket_scan_attempts",
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.CreateModel(
            name="SeatHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_holds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holds",
                        to="eventra.seat",
                    ),
                ),
            ],
            options={
                "db_table": "seat_holds",
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="seat_holds_expires_e81062_idx"
                    )
                ],
            },
        ),
    ]
