# Generated by Django 4.2.30 on 2026-09-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventra", "0004_backfill_venue"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Admin approval gate (FR-A4) — separate from is_published.",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="Organizer-controlled draft/publish toggle."
            ),
        ),
    ]
