# Generated by Django 4.2.30 on 2026-09-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventra", "0009_alter_venue_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("live_concert", "Live concert"),
                    ("music_festival", "Music festival"),
                    ("dj_night", "DJ / club night"),
                    ("classical_recital", "Classical recital"),
                    ("devotional_music", "Devotional / bhajan evening"),
                    ("tribute_show", "Tribute show"),
                    ("open_mic_music", "Open mic (music)"),
                    ("cricket_match", "Cricket match"),
                    ("football_match", "Football match"),
                    ("kabaddi_match", "Kabaddi match"),
                    ("hockey_match", "Hockey match"),
                    ("basketball_game", "Basketball game"),
                    ("badminton_tournament", "Badminton tournament"),
                    ("tennis_match", "Tennis match"),
                    ("volleyball_match", "Volleyball match"),
                    ("combat_sports", "Boxing / wrestling / MMA"),
                    ("motorsport", "Motorsport race"),
                    ("marathon", "Marathon / fun run"),
                    ("esports_tournament", "Esports tournament"),
                    ("film_screening", "Film screening"),
                    ("film_premiere", "Film premiere"),
                    ("film_festival", "Film festival"),
                    ("special_format_screening", "IMAX / 4DX special screening"),
                    ("documentary_screening", "Documentary screening"),
                    ("play", "Play / drama"),
                    ("musical", "Musical"),
                    ("dance_performance", "Dance performance"),
                    ("opera", "Opera"),
                    ("magic_show", "Magic show"),
                    ("kids_show", "Children's show"),
                    ("standup_comedy", "Stand-up comedy"),
                    ("improv_comedy", "Improv comedy"),
                    ("comedy_open_mic", "Comedy open mic"),
                    ("sketch_comedy", "Sketch comedy"),
                    ("conference", "Conference"),
                    ("trade_show", "Trade show / exhibition"),
                    ("workshop", "Workshop / masterclass"),
                    ("product_launch", "Product launch"),
                    ("art_exhibition", "Art exhibition"),
                    ("book_fair", "Book fair"),
                    ("career_fair", "Career fair"),
                    ("hackathon", "Hackathon"),
                    ("meetup", "Meetup / networking"),
                    ("food_festival", "Food festival"),
                    ("chefs_table", "Chef's table"),
                    ("tasting_event", "Wine / beverage tasting"),
                    ("supper_club", "Supper club"),
                    ("brunch", "Brunch party"),
                    ("cooking_class", "Cooking class"),
                ],
                db_index=True,
                default="",
                max_length=40,
            ),
        ),
    ]
