# Generated by Django 4.2.30 on 2026-09-21 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("zesty", "0001_initial"),
    ]

    # NOTE: this migration was auto-generated by `makemigrations`, which also
    # picked up pre-existing drift between 0001_initial and the live schema
    # (the DB was originally provisioned from database_create.sql, not these
    # migration files — see Phase 0 of the audit). Confirmed against the live
    # DB: `deliverytracking.eta`, `order.actual_delivery` and `order.payment`
    # do not exist as columns, and the AddField/AlterField operations below
    # already match the live schema exactly. Those operations are wrapped in
    # SeparateDatabaseAndState so Django's migration *state* catches up to
    # models.py without issuing DDL for columns that don't need to change.
    # Only the two CreateModel operations (Cart, CartItem) are real, new
    # tables and run against the database normally.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="deliverytracking",
                    name="eta",
                ),
                migrations.RemoveField(
                    model_name="order",
                    name="actual_delivery",
                ),
                migrations.RemoveField(
                    model_name="order",
                    name="payment",
                ),
                migrations.AddField(
                    model_name="deliverytracking",
                    name="delivery_partner_avatar_url",
                    field=models.CharField(blank=True, default="", max_length=1000),
                ),
                migrations.AddField(
                    model_name="deliverytracking",
                    name="status_timeline",
                    field=models.JSONField(blank=True, default=list),
                ),
                migrations.AddField(
                    model_name="order",
                    name="payment_method",
                    field=models.CharField(default="cod", max_length=10),
                ),
                migrations.AddField(
                    model_name="order",
                    name="payment_status",
                    field=models.CharField(default="pending", max_length=10),
                ),
                migrations.AddField(
                    model_name="orderitem",
                    name="customizations",
                    field=models.JSONField(blank=True, default=dict),
                ),
                migrations.AlterField(
                    model_name="deliverytracking",
                    name="latitude",
                    field=models.DecimalField(
                        blank=True,
                        db_column="current_lat",
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="deliverytracking",
                    name="longitude",
                    field=models.DecimalField(
                        blank=True,
                        db_column="current_lng",
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="order",
                    name="delivery_address",
                    field=models.JSONField(blank=True, default=dict),
                ),
                migrations.AlterField(
                    model_name="order",
                    name="estimated_delivery",
                    field=models.DateTimeField(
                        blank=True, db_column="estimated_delivery_time", null=True
                    ),
                ),
                migrations.AlterField(
                    model_name="order",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                migrations.AlterField(
                    model_name="order",
                    name="total",
                    field=models.DecimalField(
                        db_column="total_amount", decimal_places=2, default=0, max_digits=10
                    ),
                ),
                migrations.AlterField(
                    model_name="orderitem",
                    name="total",
                    field=models.DecimalField(
                        db_column="total_price", decimal_places=2, max_digits=10
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set on first item added; cart is restricted to a single restaurant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="zesty.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "carts",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="zesty.cart",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="zesty.menuitem",
                    ),
                ),
            ],
            options={
                "db_table": "cart_items",
                "unique_together": {("cart", "menu_item")},
            },
        ),
    ]
