# Generated by Django 4.2.30 on 2026-09-21 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zesty", "0002_cart_remove_deliverytracking_eta_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="zesty.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_status_history",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="MenuItemPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="zesty.menuitem",
                    ),
                ),
            ],
            options={
                "db_table": "menu_item_price_history",
                "ordering": ["-changed_at"],
            },
        ),
    ]
