# Generated by Django 4.2.30 on 2026-09-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zesty", "0004_restaurant_catalog_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="cuisine",
            field=models.CharField(
                blank=True,
                help_text="Primary cuisine, for catalog filtering",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="image_url",
            field=models.URLField(
                blank=True, help_text="External image URL fallback", max_length=1000
            ),
        ),
    ]
