# Generated by Django 4.2.30 on 2026-09-22 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenerationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seed", models.IntegerField()),
                ("scale", models.FloatField(default=1.0)),
                ("months", models.IntegerField(default=18)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "datagen_run",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PlantedAnomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("bulk_booking_burst", "Bulk Booking Burst"),
                            ("improbable_value", "Improbable Value"),
                            ("payment_retry_storm", "Payment Retry Storm"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target_type", models.CharField(max_length=20)),
                ("target_id", models.CharField(max_length=64)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planted_anomalies",
                        to="datagen.generationrun",
                    ),
                ),
            ],
            options={
                "db_table": "datagen_planted_anomaly",
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="datagen_pla_target__37e8d0_idx",
                    )
                ],
            },
        ),
    ]
